# Generated by Django 5.0.2 on 2024-03-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
