# Generated by Django 5.0.2 on 2024-03-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsApp', '0002_user_is_guest_alter_user_is_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Incident_Name', models.CharField(max_length=100)),
                ('Incident_Type', models.CharField(choices=[('Fire', 'Fire'), ('Rescue', 'Rescue'), ('Medical Emergency', 'Medical Emergency')], max_length=100)),
                ('Incident_Location', models.CharField(max_length=100)),
                ('Date_and_Time_of_Incident', models.DateTimeField()),
                ('Weather_Conditions', models.CharField(max_length=200)),
                ('Names_and_IDsof_Responding_Personnel', models.CharField(max_length=100)),
                ('Roles_and_Responsibilities_Assigned', models.CharField(max_length=200)),
                ('Injured_or_Affected_Individuals', models.CharField(max_length=100)),
                ('Equipment_Used', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='IncidentImage/')),
            ],
        ),
    ]
