# Generated by Django 5.0.2 on 2024-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsApp', '0003_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Date_and_Time_of_Incident',
            field=models.DateField(auto_now=True),
        ),
    ]
